### ISSUE TITLE
Question about prototype

### ISSUE THREAD

**Issue by unrealMJ** [HeimingX/semi_seg_proto#1]
Congratulations on your nips~

I have some questions about prototype. You set multi prototypes for a single class, I'm wondering whether the prototypes will collapse, i.e., only several of them are making contributions. Have you make some visualization?

If you can speak chinese, please reply in chinese, just for convenience.... thanks.

**Comment by HeimingX** [comment]
Hi, thanks for your interest in our work.

An ablation study of the number of prototypes has been presented in Figure3 of our paper. It shows that the performance tends to be saturated when num(proto) >= 4  which somehow implies that too many prototypes may collapse.  Regarding the visualization, please refer to Figure2(c).
